[package]
name = "zephyr-tools"
version = "0.1.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
pico-args = "0.5.0"
rusb = "0.9.1"
serde_json = "1.0.73"
serialport = "4.0.1"
