[package]
name = "zephyr-tools"
version = "0.1.8"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.22"
pico-args = "0.5.0"
rusb = "0.9.1"
serde_json = "1.0.86"
serialport = "4.2.0"
