[package]
name = "zephyr-tools-monitor"
version = "0.1.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
pico-args = "0.4.2"
serde_json = "1.0.73"
serialport = "4.0.1"
